const bl = (id, n, v, c) => `<div class="bl"><span>${n}</span><div class="bar"><i id="${id}i" style="width:${v}%;background:${c}"></i></div><b id="${id}v">${Math.round(v)}</b></div>`;
const badges = n => traitsOf(n).map(k => `<span class="bdg">${TR[k][0]}</span>`).join('');
function spark(h) { const m = Math.max(...h), n = Math.min(...h), w = h.length > 1 ? 280 / (h.length - 1) : 0; return `<svg viewBox="0 0 280 40" width="100%" height="40"><polyline fill="none" stroke="var(--ac2)" stroke-width="2.5" stroke-linejoin="round" points="${h.map((v, i) => (i * w) + ',' + (36 - (m == n ? 18 : (v - n) / (m - n) * 32))).join(' ')}"/></svg>` }
const jb = (k, id, txt) => { const j = job(k, id); return j ? `<div class="bar" style="margin:6px 0 2px"><i data-j="${k + id}" style="width:${100 * (j.tot - j.left) / j.tot}%;background:var(--ac2)"></i></div><small>${txt} · <span data-l="${k + id}">${j.left.toFixed(1)}</span> days left</small>` : '' };
function panel() {
    const t = S.tab;
    if (t == 'b') return (Object.keys(S.spz || {}).length ? `<div class="it" style="display:block"><b>🏆 Your specializations</b><br>${Object.keys(S.spz).map(k => `<span class="bdg">${SPZ[k][0]}</span>`).join('')}</div>` : '') + secChips() + SECT.filter(q => BSEC == 'all' || BSEC == q[0]).map(q => `<div class="ov" style="margin-top:10px">${q[1]}</div><small>${q[2]}</small>` + B.filter(x => q[3].includes(x[0])).map(x => { const j = job('b', x[0]); return `<div class="it"><div style="flex:1">${x[1]} <b>${x[2]}</b> <span class="pips">${'●'.repeat(S.b[x[0]]) || '○'}</span><br>${j ? jb('b', x[0], 'Building L' + (S.b[x[0]] + 1)) : `<small>${x[3]} · ${5 + 2 * S.b[x[0]]} days</small>${(S.spz || {})[x[0]] ? ` <span class=\"bdg\">${SPZ[x[0]][0]}</span>` : `<br><small>★ Level 4 → ${SPZ[x[0]][0]}</small>`}`}</div><button ${j || S.gold < cost(x[0]) || S.jobs.filter(q => q.k == 'b').length >= 3 ? 'disabled' : ''} onclick="buy('${x[0]}')">${j ? '⏳' : money(cost(x[0]))}</button></div>` }).join('')).join('') + '<small>Up to 3 construction projects at once.</small>' + econHtml();
    if (t == 'p') return PR.filter(p => !p.p || p.p == S.party).map(p => { const j = job('p', p.id); return `<div class="it"><div style="flex:1"><b>${p.n}</b><br>${j ? jb('p', p.id, 'Rolling out') : `<small>${p.d} · −${money(pc(p))}/qtr · 4-day rollout</small>`}</div><button class="${S.prog[p.id] ? 'p' : ''}" ${j || (!S.prog[p.id] && S.gold < pc(p)) ? 'disabled' : ''} onclick="tp('${p.id}')">${j ? '⏳' : S.prog[p.id] ? 'ON ✓' : 'Start'}</button></div>` }).join('');
    if (t == 'l' && S.lt == 'c') return lawSeg() + congressHtml();
    if (t == 'l') return lawSeg() + govNote() + '<small>⭐ Laws are exclusive to your party. Laws that fit your ideology are cheaper and strengthen your seats; laws against it cost more and can split your party. A bill is debated 8 days, then the council votes by seats and ideology.</small>' + LW.filter(l => !l.p || l.p == S.party).map(l => { const j = job('l', l.id); return `<div class="it"><div style="flex:1"><b>${l.p ? '⭐ ' : ''}${l.n}</b><br>${j ? jb('l', l.id, 'Under debate') : `<small>${l.d} · ${lch(l)}% to pass${tag(l)}</small>`}</div>${S.law[l.id] ? '<b>✔ Law</b>' : `<button ${j || S.gold < lc(l) ? 'disabled' : ''} onclick="propose('${l.id}')">${j ? '⏳' : money(lc(l))}</button>`}</div>` }).join('');
    if (t == 'i') return unitsHtml();
    if (t == 'f') return forcesHtml().replace(/ompanys\b/g, 'ompanies');
    if (t == 'n') return nationsHtml();
    if (t == 'w') return S.lv < 2 ? powerHtml() : '<small>👑 The pathways to power are for governors and regional leaders. You already lead the nation.</small>';
    if (t == 'c') {
        const ks = Object.keys(S.seats).sort((a, b) => S.seats[b] - S.seats[a]), cd = 14 - (S.day - S.lobCd);
        return natHtml() + `<div class="ov">${['Provincial council · one seat per city mayor', 'Regional council · one seat per province ' + LOC.gv, 'National council · one seat per regional head'][S.lv || 0]}</div><div class="seats">${ks.map(k => `<i style="width:${S.seats[k]}%;background:${PT[k].c}" title="${PT[k].n}"></i>`).join('')}</div>` + `<small>${S.rv ? '📊 Last annual review (' + dstr(S.rv.day) + '): rating <b>' + S.rv.rt + '</b> · ' + S.rv.det + '<br>' + S.rv.txt : '📊 The council is reviewed once a year, based on happiness, approval, integrity and border safety.'}<br>Next review in ${84 - S.day % 84} days.</small>` + ks.map(k => `<div class="it"><div><img src="${PT[k].lg}" alt="" style="width:26px;height:26px;vertical-align:middle;margin-right:6px;object-fit:contain"><b>${PT[k].n}</b>${k == S.party ? ' ⭐' : ''}<br><small>${PT[k].d}</small></div><b>${S.seats[k].toFixed(0)}%</b></div>`).join('') + `<div style="background:var(--bg);border-radius:12px;padding:10px;margin-top:8px"><img src="${PT[S.party].lg}" alt="" style="width:48px;height:48px;object-fit:contain;float:left;margin:0 10px 4px 0"><b style="color:${PT[S.party].c}">${PT[S.party].n}</b><br><small>👍 ${PT[S.party].pk}<br>👎 ${PT[S.party].ck}</small></div><button class="big" ${S.gold < pa() || S.day - S.aCd < 28 ? 'disabled' : ''} onclick="pact()">⭐ ${PT[S.party].act.n}${pa() ? ' (' + money(pa()) + ')' : ''}${S.day - S.aCd < 28 ? ' · ' + (28 - S.day + S.aCd) + 'd cooldown' : ''}</button><p><small>${PT[S.party].act.d}</small></p><button class="big" ${S.gold < Math.round(40 * pm()) || cd > 0 ? 'disabled' : ''} onclick="lobby()">🤝 Lobby the council (${money(Math.round(40 * pm()))})${cd > 0 ? ' · ' + cd + 'd cooldown' : ''}</button>`
    }
    return MS.filter(m => !m.p || m.p == S.party).map(m => `<div class="it"><div>${S.done[m.id] ? '✅' : '🎯'} <b>${mt(m.t)}</b></div><small>${S.done[m.id] ? 'Done' : '+' + money(m.r)}</small></div>`).join('') + '<p><small>Development trend</small></p>' + spark(S.h)
}
function ui() {
    ensF(); ensD(); ensC(); ensP(); $('app').dataset.step = 'game'; const inc = income(), ir = ira(), up = upkeep(), el = (x => x < S.end ? x : 0)(Math.floor(S.day / 252 + 1) * 252), u = S.t / CYC;
    side.innerHTML = `<div class="card"><div style="margin-bottom:8px"><button onclick="toMenu()" title="Save and return to the main menu">← Back to menu</button></div><div class="row between"><div><div class="ov"><img src="${pt().lg}" alt="" style="width:20px;height:20px;vertical-align:-5px;margin-right:5px">${TT[S.lv || 0]} · <span style="color:${pt().c}">${pt().n}</span></div><h2>${S.lv == 2 ? C[CTRY].flag + ' ' : ''}${S.v.n}</h2></div><div class="rk">#${rank()}<small>/${all.length}</small></div></div>${badges(S.v.n)}<span class="bdg">🛂 Border: ${EXN[S.ex]}</span>${S.sys ? `<span class="bdg">🏛️ ${SY[S.party].n}</span>` : ''}${S.dyn && S.dt == S.lv ? '<span class="bdg">👪 Dynasty</span>' : ''}
<div class="clk"><b id="clk">${clock(u)}</b><small id="dt">${dstr(S.day)}</small></div><div class="prog" style="margin-top:4px"><i id="tdf" style="width:${u * 100}%"></i></div>
<small>Term ${Math.round(S.day / S.end * 100)}%${el ? ' · election in ' + (el - S.day) + ' days' : ''}</small>
<div class="tiles"><div class="t"><small>${LOC.cur.sym} Treasury</small><b id="g">${money(S.gold)}</b></div><div class="t"><small>👥 Population (k)</small><b id="pop">${Math.round(S.pop).toLocaleString()}</b></div><div class="t"><small>🌾 Food</small><b id="fd">${Math.round(S.food)}</b></div><div class="t"><small>📈 Development</small><b id="dv">${S.v.dev}</b></div><div class="t"><small>🌐 HDI</small><b id="hdi">${hdi().toFixed(3)}</b></div></div>
<div class="bars">${bl('hap', '😊 Happy', S.hap, S.hap > 50 ? 'var(--ok)' : 'var(--ac)')}${bl('sup', '👍 Approval', S.sup, 'var(--ac2)')}${bl('int', '⚖️ Integrity', S.int, 'var(--gd)')}${bl('thr', '🛂 Border threat', S.thr, S.thr > 50 ? 'var(--ac)' : 'var(--gd)')}${bl('bsec', '🛡️ Border security', borderSec().score, borderSec().score >= 55 ? 'var(--ok)' : 'var(--ac)')}${cOn() ? bl('ct', '🏛️ Capital tension', S.ct, S.ct > 60 ? 'var(--ac)' : 'var(--gd)') : ''}</div>
<p><small>+${money(inc)} income · +${money(ir)} national aid · −${money(up)} upkeep = <b>${inc + ir - up >= 0 ? '+' : ''}${money(inc + ir - up)}</b> per quarter (21 days)</small></p>
<div class="seg">${['Low', 'Normal', 'High'].map((t, i) => `<button class="${S.tax == i ? 'on' : ''}" onclick="S.tax=${i};ui()">Tax: ${t}</button>`).join('')}</div></div>
${S.over ? `<div class="card ev"><h2>${S.msg}</h2><p>Final development: ${S.v.dev} · Final HDI: ${hdi().toFixed(3)} · Goals: ${Object.keys(S.done).length}/${MS.filter(m => !m.p || m.p == S.party).length}</p><button class="p big" onclick="S=null;sel=null;build();ST='title';menu();resetV();$('night').style.opacity=0">Play again</button></div>` :
            S.ev ? `<div class="card ev"><h2 style="font-size:18px">${mt(S.ev.t)}</h2><small>Time is paused while you decide.</small>${S.ev.o.map((o, i) => `<button class="${i ? '' : 'p'}" ${S.gold < (o[2] || 0) ? 'disabled' : ''} onclick="pick(${i})">${mt(o[0])}</button>`).join('')}</div>` :
                `<div class="card"><div class="seg tabs">${[['b', '🏗️', 'Build'], ['p', '📋', 'Programs'], ['l', '📜', 'Laws'], ['c', '🏛️', 'Council'], ['f', '🛡️', 'Forces'], ['n', '🌐', 'Nations'], ...(S.lv < 2 ? [['w', '👑', 'Power']] : []), ['g', '🎯', 'Goals'], ['i', '🗺️', ['Cities', 'Provinces', 'Regions'][S.lv || 0]]].map(t => `<button class="${S.tab == t[0] ? 'on' : ''}" title="${t[2]}" onclick="S.tab='${t[0]}';ui()">${t[1]}<span class="lb"> ${t[2]}</span></button>`).join('')}</div>${panel()}</div>`}
<div class="card feed">${S.log.slice(0, 5).join('<br>')}</div>
${S.over ? '' : `<div class="card ctl">${SPD.map((s, i) => `<button class="${S.sp == i ? 'p' : ''}" onclick="setSp(${i})">${i ? s + '×' : '⏸'}</button>`).join('')}</div>`}`; draw(); hud(); save()
}

let ST = 'title';
function toMenu() { if (S && !S.over) { setSp(0); save() } S = null; sel = null; build(); ST = 'title'; menu(); resetV(); $('night').style.opacity = 0 }
function go(s) { ST = s; menu(); if (s == 'map') resetV() }
function menu() {
    $('app').dataset.step = ST;
    const hd = (n, t, b) => `<div class="row between"><div class="ov">New game · Step ${n} of 4 · ${t}</div>${b ? `<button onclick="go('${b}')">← Back</button>` : ''}</div>`;
    if (ST == 'title') {
        side.innerHTML = `<div class="card hero"><div class="ov">${Object.values(C).map(c => c.flag + ' ' + c.name).join(' · ')}</div><img class="logo logo-hero" src="assets/logo.png" alt="President or Rebel – Beta Version" width="200" height="200"><h1 class="sr">Province Governor</h1><p>Lead a province (or state or district) of the Philippines, Malaysia, Brunei or Singapore for 10 years in real time: a day lasts 4 minutes of light and 1 minute of night at 1× speed. Recruit police, soldiers and local militia to guard your borders, run programs, pass laws through a party-split council, survive typhoons and monsoon floods, and win elections. Finish at the top in development to win votes for Regional Representative, then President or Prime Minister, where you can rewrite how the country is run.</p>
<div class="ov">Difficulty</div><div class="seg">${Object.keys(DF).map(k => `<button class="${DIF == k ? 'on' : ''}" onclick="DIF='${k}';menu()">${DF[k].n}</button>`).join('')}</div><small>${DF[DIF].d}</small><button class="p big" onclick="setCountry(CTRY);go('country')">▶ New game</button><div class="ov" style="margin-top:14px">Saved games · 2 slots max</div>${slotsHtml()}</div>`; return
    }
    if (ST == 'country') { side.innerHTML = `<div class="card">${hd(2, 'Choose your country', 'title')}<p><small>Which country will you start in?</small></p>${Object.keys(C).map(k => `<div class="pcard ${CTRY == k ? 'on' : ''}" onclick="pickCountry('${k}')"><svg class="cth" viewBox="${C[k].bb.join(' ')}" aria-hidden="true">${thumb(k)}</svg><div><b>${C[k].flag} ${C[k].name}</b><br><small>${C[k].pv.length} ${C[k].unit || 'provinces/states'} · start funds ${money(C[k].gold, k)}<br>${C[k].note}</small></div></div>`).join('')}</div><button class="p next" onclick="go('party')">Next: choose your party →</button>`; return }
    if (ST == 'party') { side.innerHTML = `<div class="card">${hd(3, 'Choose your party', 'country')}${Object.keys(PT).map(k => `<div class="pcard ${PARTY == k ? 'on' : ''}" onclick="PARTY='${k}';menu()"><img class="lgo" src="${PT[k].lg}" alt=""><div><b>${PT[k].n}</b><br><small>${PT[k].d}<br>👍 ${PT[k].pk}<br>👎 ${PT[k].ck}</small></div></div>`).join('')}</div><button class="p next" onclick="go('map')">Next: choose your province →</button>`; return }
    side.innerHTML = `<div class="card">${hd(4, 'Province & host city', 'party')}<div class="row" style="margin:6px 0"><img class="lgo" style="width:30px;height:30px" src="${PT[PARTY].lg}" alt=""><small>${PT[PARTY].n} · ${DF[DIF].n}</small></div>${sel ? `<div class="ov">Selected</div><h2>${sel.n}</h2>${badges(sel.n)}<p>Population ${sel.pop.toLocaleString()}k · Development ${sel.dev}</p>${rulingHtml(sel)}${cityPick()}${newBtn()}` : '<p>👆 Tap a province on the map. Pinch or scroll to zoom, drag to move.</p>'}</div>`; draw()
}
function draw() {
    const z = V.w / fitW(); map.setAttribute('viewBox', vb().join(' ')); map.style.setProperty('--z', z);
    const ar = q => { let a = 0; for (let j = 0; j < q.length; j += 2) { const k = (j + 2) % q.length; a += q[j] * q[k + 1] - q[k] * q[j + 1] } return Math.abs(a / 2) };
    if (!map.querySelector('#pvg')) { map.innerHTML = '<g id="nbg"></g><g id="pvg"></g><g id="nbo"></g>'; nbDirty = true }
    map.classList.toggle('dipl', dOn()); if (dOn()) nbDirty = true;
    if (nbDirty) { map.querySelector('#nbg').innerHTML = nbHtml(false); map.querySelector('#nbo').innerHTML = nbHtml(true) + nbLab(); nbDirty = false }
    const pvg = map.querySelector('#pvg'); pvg.innerHTML = all.map((v, i) => {
        const d = v.r.map(q => { let t = 'M'; for (let j = 0; j < q.length; j += 2)t += (j ? 'L' : '') + q[j] + ',' + q[j + 1]; return t + 'Z' }).join('');
        const q = v.r[0], A = ar(q); let cx = 0, cy = 0; for (let j = 0; j < q.length; j += 2) { cx += q[j]; cy += q[j + 1] } cx /= q.length / 2; cy /= q.length / 2;
        return `<path data-i="${i}" d="${d}" fill="${col(v.dev)}" class="${S && TM.includes(v) ? 'me' : sel === v ? 'sel' : ''}"><title>${v.n} (dev ${v.dev}, HDI ${v === S?.v ? hdi().toFixed(3) : hdiOf(v.dev).toFixed(3)})</title></path>${A > 3500 * z * z ? `<text x="${cx}" y="${cy}" style="font-size:${(A > 12000 ? 22 : 15) * z}px">${v.n}</text>` : ''}`
    }).join('');
    pvg.querySelectorAll('path').forEach(p => p.onclick = () => { if (!S && !moved) { sel = all[p.dataset.i]; hqI = -1; menu() } });
    if (dOn()) map.querySelectorAll('[data-c]').forEach(p => p.onclick = () => { if (!moved && !S.over) { S.tab = 'n'; S.dc = p.dataset.c; ui() } })
}
