// =====================================================================
//  DIFFICULTY & REALISTIC MODE (starts in 2000 and replays the real events of the era)
// =====================================================================
const dfm = k => ((DF[S && S.dif] || DF.n)[k]), yrNow = () => (S.y0 || 2026) + Math.floor(S.day / 84);
const RE = [
    { id: 'sep11', y: 2001, m: 9, h: '9/11 attacks shake the world: a global security alert and a tourism slump.', mc: [['inc', -.04, 84]], nr: -2, t: '🌍 The September 11 attacks trigger a global security alert. Visitors cancel trips.', o: [['Raise the border alert (−{40} gold, threat −8)', s => { s.gold -= g(40); s.thr -= 8; return 'Border posts went on high alert.' }, 40], ['Business as usual (threat +5)', s => { s.thr += 5; return 'Critics say you are complacent.' }]] },
    { id: 'sars', y: 2003, m: 3, h: 'SARS spreads across Asia. Hospitals fill up.', mc: [['inc', -.03, 56]], nr: -2, t: '😷 SARS has spread across Asia and cases are reported near your territory.', o: [['Strict quarantine (−{50} gold, happiness −3, lives saved)', s => { s.gold -= g(50); s.hap -= 3; return 'Quarantine contained the outbreak.' }, 50], ['Keep everything open (happiness −8, population −1%)', s => { s.hap -= 8; s.pop *= .99; return 'The outbreak hit hard.' }]] },
    { id: 'tsunami', y: 2004, m: 12, h: 'The Indian Ocean tsunami kills hundreds of thousands. The region mobilises aid.', nr: 0, t: '🌊 The Indian Ocean tsunami devastates coastlines across the region. Relief appeals go out.', o: [['Send relief teams (−{40} gold, integrity +2, approval +3)', s => { s.gold -= g(40); s.int += 2; s.sup += 3; return 'Your relief teams earned praise.' }, 40], ['Check your own coastal defenses (−{20} gold, threat −2)', s => { s.gold -= g(20); s.thr -= 2; return 'Coastal warning systems were upgraded.' }, 20]] },
    { id: 'gfc', y: 2008, m: 9, h: 'The global financial crisis hits. Exports and remittances fall.', mc: [['inc', -.12, 168]], nr: -8, t: '📉 Lehman Brothers collapses. The global financial crisis hits exports, jobs and remittances.', o: [['Stimulus spending (−{80} gold, happiness +4)', s => { s.gold -= g(80); s.hap += 4; return 'Stimulus cushioned the shock.' }, 80], ['Austerity (+{30} gold, happiness −3, approval −3)', s => { s.gold += g(30); s.hap -= 3; s.sup -= 3; return 'Belt-tightening angered voters.' }]] },
    { id: 'ondoy', y: 2009, m: 9, c: ['PH'], h: 'Typhoon Ondoy (Ketsana) floods Metro Manila and Luzon.', mc: [['inc', -.03, 42]], nr: -3, t: '🌀 Typhoon Ondoy dumps a month of rain in hours. Flood waters rise across Luzon.', o: [['Open relief centers (−{50} gold, approval +3)', s => { s.gold -= g(50); s.sup += 3; return 'Relief centers saved many lives.' }, 50], ['Leave it to national agencies (approval −3, happiness −3)', s => { s.sup -= 3; s.hap -= 3; return 'Residents felt abandoned.' }]] },
    { id: 'haiyan', y: 2013, m: 11, c: ['PH'], h: 'Super Typhoon Haiyan (Yolanda) devastates the central Philippines.', mc: [['inc', -.03, 56]], nr: -4, t: '🌪️ Super Typhoon Haiyan, one of the strongest storms ever, makes landfall.', o: [['Send aid and rescue teams (−{60} gold, approval +4, integrity +2)', s => { s.gold -= g(60); s.sup += 4; s.int += 2; return 'Your teams were among the first to arrive.' }, 60], ['Focus on your own territory (happiness −2)', s => { s.hap -= 2; return 'Others carried the relief effort.' }]] },
    { id: 'oil', y: 2014, m: 7, h: 'Oil and commodity prices collapse.', t: '🛢️ Oil prices collapse by half in a few months, squeezing budgets.', o: [['Cut spending (+{20} gold, happiness −2)', s => { s.gold += g(20); s.hap -= 2; return 'Spending cuts calmed the budget.' }], ['Borrow to ride it out (−{30} gold, happiness +1)', s => { s.gold -= g(30); s.hap += 1; return 'You bridged the gap with loans.' }, 30]] },
    { id: 'floods', y: 2014, m: 12, c: ['MY', 'BN'], h: 'Severe monsoon floods hit the east coast.', mc: [['inc', -.03, 42]], nr: -2, t: '🌊 Severe monsoon floods submerge towns on the coast.', o: [['Relief and rebuilding fund (−{50} gold, approval +3)', s => { s.gold -= g(50); s.sup += 3; return 'Rebuilding began quickly.' }, 50], ['Wait for the waters to recede (happiness −3)', s => { s.hap -= 3; return 'Many were left stranded.' }]] },
    { id: 'covid', y: 2020, m: 3, h: 'COVID-19 becomes a global pandemic. Borders close and economies stall.', mc: [['inc', -.15, 168]], nr: -10, t: '🦠 COVID-19 is declared a pandemic. Borders close, markets stall.', o: [['Strict lockdown (−{70} gold, happiness −4, income hit)', s => { s.gold -= g(70); s.hap -= 4; return 'The lockdown slowed infections.' }, 70], ['Open with testing and hospitals (−{40} gold)', s => { s.gold -= g(40); const k = S.b.hospital || 0; s.hap -= Math.max(0, 8 - k * 2); return k >= 2 ? 'Your hospitals coped well.' : 'Hospitals were overwhelmed.' }, 40]] },
    { id: 'infl', y: 2022, m: 2, h: 'An energy and food price shock drives inflation worldwide.', mc: [['inc', -.05, 168]], nr: -4, t: '⛽ War in Europe drives energy and food prices through the roof.', o: [['Subsidize fuel and food (−{60} gold, happiness +3)', s => { s.gold -= g(60); s.hap += 3; return 'Subsidies eased the pain.' }, 60], ['Let prices float (happiness −4, approval −2)', s => { s.hap -= 4; s.sup -= 2; return 'Households felt the squeeze.' }]] }];
const g = x => Math.round(x * pm());
function histTick() {
    if (!S.real) return; S.rtd = S.rtd || {}; S.mc = (S.mc || []).filter(m => m.until > S.day);
    RE.forEach(e => {
        const d = (e.y - 2000) * 84 + (e.m - 1) * 7; if (S.rtd[e.id] || S.day < d || S.day > d + 28 || (e.c && !e.c.includes(CTRY))) return; S.rtd[e.id] = 1;
        (e.mc || []).forEach(([k, v, n]) => S.mc.push({ k, v: v * (CTRY == 'BN' && e.id == 'oil' ? 2 : CTRY == 'SG' && (e.id == 'sars' || e.id == 'gfc') ? 1.5 : 1), until: S.day + n })); if (cOn() && e.nr) S.nrt = cl(S.nrt + e.nr, 15, 85);
        toast('📰 ' + e.y + ': ' + e.h);
        if (!S.pev) S.pev = { t: e.t, o: e.o.map(([l, f, c]) => [l.replace(/\{(\d+)\}/g, (_, n) => g(+n)), f, c ? g(c) : 0]) }
    })
}
function nationsHtml() {
    ensD();
    if (!dOn()) return `<small>🌐 <b>Diplomacy unlocks when you become President.</b> Then you can open talks, sign trade and border-security pacts, patrol borders jointly, send peacekeepers and manage rivalries with every nation on the map.</small>` + Object.keys(NATS).filter(k => DBASE[CTRY] && DBASE[CTRY][k]).map(k => `<div class="it"><div style="flex:1">${NATS[k][1]} <b>${NATS[k][0]}</b>${DBASE[CTRY][k][1] > .25 ? ' <small>· shares a border or sea</small>' : ''}</div><small>🔒</small></div>`).join('');
    const ks = dnat().sort((a, b) => S.dip[b].r - S.dip[a].r), tr = ks.filter(k => S.dip[k].tr).length, pa = ks.filter(k => S.dip[k].pa || S.dip[k].jp).length;
    let h = `<div class="it" style="display:block"><b>${C[CTRY].flag} ${LOC.nat}</b><br><small>Your nation · 👥 ${Math.round(S.pop).toLocaleString()}k · 📈 development ${S.v.dev} · 🛡️ ${menAll().toLocaleString()} personnel</small></div>`;
    h += `<small>💱 ${tr} trade deal${tr == 1 ? '' : 's'} (income +${Math.round(dipI() * 100)}%) · 🛡️ ${pa} security agreement${pa == 1 ? '' : 's'} (border threat ${dipT() <= 0 ? '' : '+'}${dipT().toFixed(2)}/day from diplomacy). Click a country on the map or here to deal with it. One diplomatic move per country per week.</small>`;
    h += ks.map(k => {
        const d = S.dip[k], on = S.dc == k, adj = DBASE[CTRY][k][1] > .25, tags = (d.tr ? '💱 ' : '') + (d.pa ? '🛡️ ' : '') + (d.jp ? '🚓 ' : '') + (S.pk.some(m => m.c == k) ? '🕊️ ' : '');
        let x = `<div class="it" style="display:block;cursor:pointer" onclick="S.dc=${on ? 'null' : `'${k}'`};ui()"><div class="row between"><b>${NATS[k][1]} ${NATS[k][0]}${adj ? ' <small>· border</small>' : ''}</b><span style="color:${dCol(d.r)}"><b>${dLab(d.r)}</b> ${Math.round(d.r)}</span></div><div class="bar" style="margin:4px 0"><i style="width:${(d.r + 100) / 2}%;background:${dCol(d.r)}"></i></div><small>${tags}${on ? '' : 'Tap for actions'}</small>`;
        if (on) {
            x += `<div onclick="event.stopPropagation()">` + DA.filter(a => !a.adj || adj).map(a => {
                const c = Math.round(a.c * pm()), have = a.once && d[a.once], why = dCls(d) ? 'Wait ' + (7 - (S.day - d.cd)) + 'd' : have ? '' : a.r && d.r < a.r ? 'Needs ' + a.r + '+' : '';
                return `<div class="row between" style="margin-top:6px;gap:8px"><div style="flex:1"><b>${a.ic} ${a.n}</b><br><small>${a.d}</small></div>` + (have ? `<button onclick="dend('${k}','${a.once}')">End</button>` : `<button ${why || S.gold < c ? 'disabled' : ''} onclick="dact('${k}','${a.id}')">${why || (c ? money(c) : 'Free')}</button>`) + `</div>`
            }).join('');
            const busy = S.pk.some(m => m.c == k);
            x += `<div style="margin-top:8px"><b>🕊️ Send peacekeepers</b><br><small>Free military formations serve abroad for 42 days (hazard pay and transport cost 1.5× a quarter's pay). +10 relations now, +6 when they return.${busy ? ' A mission is already there.' : ''}</small><div class="row" style="margin-top:4px;gap:6px;flex-wrap:wrap">` + FT.filter(f => f.id != 'sq').map(f => { const c = fmPayQ('mil', f.id) * 1.5; return `<button ${busy || dCls(d) || freeF('mil', f.id) < 1 || S.gold < c ? 'disabled' : ''} onclick="sendPK('${k}','${f.id}')">${f.n} · ${money(c)}</button>` }).join('') + `</div></div></div>`
        }
        return x + `</div>`
    }).join('');
    return h
}
