function save() { try { if (!S || !S.slot) return; if (S.over) { localStorage.removeItem(SK(S.slot)); return } if (!S.ev) { const { v, c, ...r } = S; localStorage.setItem(SK(S.slot), JSON.stringify({ r, vi: S.hi, d: all.map(x => x.dev), ts: Date.now(), k: CTRY })) } } catch (e) { } }
const readSlot = n => { try { const j = JSON.parse(localStorage.getItem(SK(n))); return j && j.r && j.d ? j : null } catch (e) { return null } };
const slotName = j => ((C[j.k || 'PH'] || C.PH).pv[j.vi] || [])[0], hasSave = () => [1, 2].some(readSlot);
function migrate() { try { const o = localStorage.getItem(KEY); if (!o) return; const f = [1, 2].find(n => !localStorage.getItem(SK(n))); if (f) { localStorage.setItem(SK(f), o); localStorage.removeItem(KEY) } } catch (e) { } }
function cont(n) { try { const j = readSlot(n); if (!j) throw 0; if ((j.k || 'PH') != CTRY || all.length != j.d.length) setCountry(j.k || 'PH'); all.forEach((x, i) => x.dev = j.d[i]); S = Object.assign(j.r, { v: all[j.vi], c: C[CTRY], slot: n, hi: j.vi }); S.lv = S.lv || 0; S.end = S.end || 840; S.sys = S.sys || 0; S.dyn = S.dyn || 0; S.dt = S.dt || 0; S.v = terr(); ensF(); ensD(); ensC(); ensP(); if (!S.cities) { S.cities = S.lv ? tierUnits() : startUnits(S.v, 0, S.party); sync() } ui(); S.lv ? resetV() : focusV(S.v) } catch (e) { S = null; try { localStorage.removeItem(SK(n)) } catch (_) { } menu() } }
function newGame() { if (hqI < 0) return; const f = [1, 2].find(n => !readSlot(n)); if (f) start(f); else { askSlot = true; menu() } }
function delSlot(n) { if (delAsk !== n) { delAsk = n; menu(); setTimeout(() => { if (delAsk == n && !S) { delAsk = 0; menu() } }, 3000); return } try { localStorage.removeItem(SK(n)) } catch (e) { } delAsk = 0; menu() }
const ago = t => { if (!t) return 'Saved earlier'; const m = Math.round((Date.now() - t) / 6e4); return m < 1 ? 'Saved just now' : m < 60 ? 'Saved ' + m + ' min ago' : m < 1440 ? 'Saved ' + Math.round(m / 60) + ' h ago' : 'Saved ' + new Date(t).toLocaleDateString() };
const slotsHtml = () => [1, 2].map(n => { const j = readSlot(n); if (!j) return `<div class="slot empty"><div class="sl-n">Slot ${n}</div><div style="flex:1"><small>Empty</small></div></div>`; const sn = slotName(j), pa = PT[j.r.party]; return `<div class="slot"><div class="sl-n">Slot ${n}</div><div style="flex:1;min-width:0"><b>${((C[j.k || 'PH'] || {}).flag || '') + ' ' + (sn || 'Saved game')}</b><br><small>${pa ? pa.n + ' · ' : ''}${dstr(j.r.day)} · ${money(Math.round(j.r.gold), j.k || 'PH')}<br>${ago(j.ts)}</small></div><button class="p" onclick="cont(${n})">▶ Continue</button><button class="del ${delAsk == n ? 'ask' : ''}" aria-label="Delete slot ${n}" onclick="delSlot(${n})">${delAsk == n ? 'Delete?' : '🗑'}</button></div>` }).join('');
const newBtn = () => askSlot ? `<p><b>Both save slots are full.</b> Pick one to overwrite:</p>${[1, 2].map(n => { const j = readSlot(n); return `<button class="big" onclick="start(${n})">Overwrite Slot ${n} · ${j && slotName(j) ? slotName(j) : 'saved game'}</button>` }).join('')}<button class="big" onclick="askSlot=false;menu()">Cancel</button>` : '<button class="p big" ' + (hqI < 0 ? 'disabled' : '') + ' onclick="newGame()">' + (hqI < 0 ? 'Choose a host city first' : 'Become governor') + '</button>';
function start(slot) {
    askSlot = false; const c = C[sel.c], d = DF[DIF], w = Object.keys(PT).filter(k => k != PARTY).map(k => [k, .5 + Math.random()]), tw = w.reduce((a, x) => a + x[1], 0), seats = { [PARTY]: 35 }; w.forEach(([k, x]) => seats[k] = 65 * x / tw);
    S = { slot, hi: all.indexOf(sel), lv: 0, rg: -1, end: 840, sys: 0, dyn: 0, dt: 0, v: sel, c, dif: DIF, real: d.real ? 1 : 0, y0: d.real ? 2000 : 2026, rtd: {}, mc: [], party: PARTY, seats, day: 0, t: 0, sp: 3, lsp: 3, jobs: [], lobCd: -99, aCd: -99, ex: exOf(sel.n), thr: 15 + exOf(sel.n) * 5, ...startF(), fb: 'pol', gold: Math.round(c.gold * d.g), food: 100, hap: 60 + c.hap, pop: sel.pop, tax: 1, prog: {}, law: {}, done: {}, sup: 50, int: 60, tab: 'b', b: {}, h: [sel.dev], log: [], ev: null, over: 0, tr: traitsOf(sel.n) };
    S.cities = startUnits(sel, hqI, PARTY); sync(); TM = [sel]; B.forEach(x => S.b[x[0]] = 0); S.hap += fx('hap'); toast('You are now ' + TT[0].toLowerCase() + ' of ' + sel.n + ' for ' + PT[PARTY].n + '.'); ui(); focusV(sel)
}
